adding components
hahays/todo.app pull request #1
Opened 2021-12-27 05:53 UTC by hahays

Hello

2021-12-27 07:28 UTC, vkhalikov requested changes

2021-12-27 07:28 UTC, vkhalikov commented on src/components/DataProvider.js
> +export const DataContext = createContext();
Если это контекст и провайдер для тудушек, то лучше будет назвать TodoContext и TodoContextProvider

2021-12-27 07:28 UTC, vkhalikov commented on src/components/DataProvider.js
> +    <DataContext.Provider value={[todos, setTodos]}>
Почему тут value массивом? Лучше сделать объектом
```
{
  todos, // или data
  setTodos,
}
```

Тогда, при желании передать в value ещё какие-то штуки, их проще будет извлекать в компонентах.

2021-12-27 07:28 UTC, vkhalikov commented on src/components/Footer.js
> +  const handleCheckAll = () => {
Можно этот функционал вынести в `DataContext`
Там были бы методы для работы с todo, такие как `checkAll`, `delete`, `add`, `check` и т.д.
Тогда в любом компоненте, где требуется изменить данные todo, можно было бы достать эти методы из контекста.

2021-12-27 07:28 UTC, vkhalikov commented on src/components/Footer.js
> +        <h1 className>Наконец-то ты фсе сделала {roma} </h1>
почему тут пустой `className`?

2021-12-27 07:28 UTC, vkhalikov commented on src/components/Footer.js
> +  const [checkAll, setCheckAll] = useState(false);
Это лучше сделать не состоянием, а определять из данных.

2021-12-27 07:28 UTC, vkhalikov commented on src/components/FormInput.js
> +export default function FormInput() {
Это не FormInput, а просто Form или TodoForm

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoList.js
> +    const newTodos = [...todos];
Правильно делаешь, что новый массив создаёшь, когда данные модифицируешь

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoList.js
> +        <TodoListItem
Тут молодец, что отдельный компонент сделал

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoList.js
> +          handleEditTodos={handleEditTodos}
`handleEditTodos` -> `onEditName`
Не очень понятно, что за `checkComplete` и `switchComplete`

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoListItem.js
> +  const [onEdit, setOnEdit] = useState(false);
`onEdit` -> `editActive` или `editModeActive`

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoListItem.js
> +  const [editValue, setEditValue] = useState(todo.name);
`currentName`

2021-12-27 07:28 UTC, vkhalikov commented on src/components/TodoListItem.js
> +  const handleSave = (id) => {
Тут id не нужно через параметры передавать.
Оно у тебя выше в пропсах уже есть.
Тогда ниже не нужно будет анонимную функцию создавать.

2021-12-27 08:27 UTC, vkhalikov commented on src/components/DataProvider.js
> +    <DataContext.Provider value={[todos, setTodos]}>
Допустим, мы добавим сюда методы для работы с данными туду, как я написал ниже.
Добавляем метод `addTodo`.
`value={[todos, setTodos, addTodo]}`
Если оставить массив, то при извлечении этих функций из массива, нам придётся соблюдать порядок.
Например, в компоненте Footer нам понадобятся только `todos` и `addTodo`:
`const [todos, setTodos, addTodo] = useContext()`
setTodos не нужен и будет подсвечиваться как неиспользованный, но без его извлечения, мы не сможем получить addTodo.

А если бы передавали объект:
`value={{ todos, setTodos, addTodo }}`
То моги бы извлекать в компонентах только нужные функции, не парясь о порядке.
`const { todos, addTodo } = useContext()`

2021-12-27 08:38 UTC, vkhalikov commented on src/components/Footer.js
> +  const [checkAll, setCheckAll] = useState(false);
Тут можно использовать метод массива `every`,  чтобы определить все ли тудушки выполнены.

2021-12-27 08:40 UTC, hahays commented on src/components/Footer.js
> +  const [checkAll, setCheckAll] = useState(false);
CheckAll > AllCheck

2021-12-27 08:50 UTC, vkhalikov commented on src/components/Footer.js
> +  const handleCheckAll = () => {
Вынеси в `DataContext` функцию `deleteTodo` и потом используй эту функцию в этом компоненте, а также в компоненте `TodoListItem`, тогда станет понятно, почему методы для работы с данными лучше держать выносить в контекст.

2021-12-27 09:01 UTC, hahays commented on src/components/TodoList.js
> +    const newTodos = [...todos];
Прочитать про модификацию данных в документации

2021-12-27 09:13 UTC, vkhalikov commented on src/components/TodoListItem.js
> +  const [editValue, setEditValue] = useState(todo.name);
или `editableValue`

2022-01-03 06:07 UTC, hahays reviewed
Done!

2022-01-03 06:10 UTC, merged